FROM ft-rails:on-build
EXPOSE 3000
CMD ["rails", "s", "-b", "0.0.0.0", "-p", "3000"]

#docker build -t ex04 .
#docker run -it --rm -p 3000:3000 ex04

# rails s: launches server
# -b 0.0.0.0: bind to all IPs on the machine
# -p3000: running on port 3000
